### ISSUE TITLE
timestamp() function returns wrong unix time 2nd round

### ISSUE THREAD

**Issue by eevora** [Naguissa/uUnixDate#3]
I have found that  when I load an unixDate(year,mes,dia,hora,minuto,seg) the timestamp is calculated wrong, it returns exactly 432000 seconds (5 days) after the right time. I assume that may be it does not have in count the leap years which have been 5 from year 2000 without counting it. What seems strange to me that if I load an unixDate(timestamp) it returns the right date... there is a fragment of the code I have used to explain better... this code is running on ESP32 microcontroller.

    uUnixDate dateA = uUnixDate(year1,mes,dia,hora,minuto,seg);
    Serial.print(dateA.year());
    Serial.print(dateA.month());
    Serial.print(dateA.day());
    Serial.print(dateA.hour());
    Serial.print(dateA.minute());
    Serial.print(dateA.second());
    Serial.print(dateA.timestamp());  
    uUnixDate dateC = uUnixDate(dateA.timestamp());
    Serial.print(dateC.year());
    Serial.print(dateC.month());
    Serial.print(dateC.day());
    Serial.print(dateC.hour());
    Serial.print(dateC.minute());
    Serial.print(dateC.second());
    Serial.print(dateC.timestamp());

// date A is 2023/7/26 23:8:18 dateA.timestamp 1690844898
// date C is 2023/7/31 23:8:18 dateC.timestamp 1690844898

for the same timestamp the 2 dates can't be different...

**Comment by eevora** [comment]
After debugging the program I realize that the problem is not about the leap years, there are months in different years that calculates good the timestamp, and months that calculate it wrong, and the difference dont increase with the years, it just recovers to the right timestamp and start again, hope this helps....

**Comment by Naguissa** [comment]
Fixest in just-created release, 1.2.0. It was a bug on setTimestamp.
